### ISSUE TITLE
NoCredentialProviders: no valid providers in chain. Deprecated.

### ISSUE THREAD

**Issue by ibuchh** [cn-terraform/terraform-aws-ecs-cluster#1]
I am trying to use your "jnonino/networking/aws" module with all default settings but as I try terraform plan, I get the following error:

============

Error: error validating provider credentials: error calling sts:GetCallerIdentity: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors

  on .terraform/modules/networking/jnonino-terraform-aws-networking-5cb82ad/main.tf line 4, in provider "aws":
   4: provider "aws" {

=============
Can you help.

**Comment by jnonino** [comment]
Hi, how are you?
Can you provide any more details about the issue?
Here is the documentation for that module: [https://registry.terraform.io/modules/cn-terraform/networking/aws/2.0.4](https://registry.terraform.io/modules/cn-terraform/networking/aws/2.0.4)

**Comment by jnonino** [comment]
@ibuchh I have been using this module on version [1.0.2](https://registry.terraform.io/modules/cn-terraform/ecs-cluster/aws/1.0.2). Please try it and let me know if it works for you. Reopen the issue if it does not.
