### ISSUE TITLE
When importing resources, terraform complains that the region is incorrect

### ISSUE THREAD

**Issue by jasiek** [cn-terraform/terraform-aws-ecs-cluster#2]
```
Error: Invalid AWS Region:

  on .terraform/modules/vp-dev-ecs/cn-terraform-terraform-aws-ecs-cluster-509b545/main.tf line 4, in provider "aws":
   4: provider "aws" {
```

Removing the provider declaration from this module solves the problem. Why is it included in the first place?

**Comment by jnonino** [comment]
Hi, I have use the module as it is on other repositories and did not have that problem. The provider is included because you can use that module alone. Check [here](https://github.com/jnonino/symmetrical-spork).
